version: "3.9"

services:
  categories:
    build: ./categories
    user: root
    working_dir: /app-categories
    container_name: blogs_categories_golang
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./categories:/app-categories
    restart: always
    depends_on:
      - db
    ports:
      - 8200:8200
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
      JWT_SECRET: secretJWT
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
  db:
    container_name: blogs_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
networks:
  default:
    name: blogs_microservices