// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/beto-ouverney/blogs-microservices/categories/server/service (interfaces: ICategoryService)

// Package mock_service is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/beto-ouverney/blogs-microservices/categories/server/entity"
	errors "github.com/beto-ouverney/blogs-microservices/categories/server/errors"
	gomock "github.com/golang/mock/gomock"
)

// MockICategoryService is a mock of ICategoryService interface.
type MockICategoryService struct {
	ctrl     *gomock.Controller
	recorder *MockICategoryServiceMockRecorder
}

// MockICategoryServiceMockRecorder is the mock recorder for MockICategoryService.
type MockICategoryServiceMockRecorder struct {
	mock *MockICategoryService
}

// NewMockICategoryService creates a new mock instance.
func NewMockICategoryService(ctrl *gomock.Controller) *MockICategoryService {
	mock := &MockICategoryService{ctrl: ctrl}
	mock.recorder = &MockICategoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoryService) EXPECT() *MockICategoryServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockICategoryService) Add(arg0 string) (*entity.Category, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(*entity.Category)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockICategoryServiceMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockICategoryService)(nil).Add), arg0)
}

// GetAll mocks base method.
func (m *MockICategoryService) GetAll() (*[]entity.Category, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]entity.Category)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICategoryServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICategoryService)(nil).GetAll))
}